services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: node:20.10
    working_dir: /app/counter
    volumes:
      - ./counter:/app/counter
    environment:
      - PORT=3003
      - REDIS_URL=redis://storage
    ports:
      - 8080:3003 
      - 3002:3002
    command: npm run dev
    depends_on:
      - storage
  library:
    image: node:20.10
    working_dir: /app
    volumes:
      - ./:/app/
    environment:
      - PORT=3002
      - COUNTER_PORT=3003
    ports:
      - 80:3002
    command: npm run dev
    depends_on:
      - counter
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false